// some api endpoints for you to test

GET http://localhost:8000/api/users/1?name=try&email=test@gmail.com
GET http://localhost:8000/api/users/1
GET http://localhost:8000/api/users/2
GET http://localhost:8000/api/users/3

POST http://localhost:8000/api/user
